name: Build

on:
  push:
    tags: [v*]
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "app"
      - name: Build
        run: |
          if [ startsWith(github.ref, 'refs/tags/') ]; then
            cargo build --verbose --release
          else
            cargo build --verbose
          fi
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            ./target/*/