name: Build

on:
  push:
    tags: [v*.*.*]
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "app"
      - name: Build
        if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
        run: cargo build
      - name: Build(release)
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: |
            ./target/*/pixelate*
            !./target/*/pixelate.d
      - name: Package
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
              7z a pixelate_"$RUNNER_OS"_x64.zip ./target/release/pixelate.exe
          else
              tar czvf pixelate_"$RUNNER_OS"_x64.tgz ./target/release/pixelate
          fi
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            ./pixelate_*_x64.*
