name: Build and Release

on:
  push:
    tags: [v*.*.*]
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: pixelate-${{ matrix.os }}
          path: ./target/release/pixelate*

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      # Packaging per OS
      - name: Package Artifacts
        run: |
          for os in ubuntu-latest macos-latest windows-latest; do
            if [ -d "pixelate-$os" ]; then
              case "$os" in
                windows-latest) 7z a pixelate_${os}.zip pixelate-$os/* ;;
                *) tar czvf pixelate_${os}.tar.gz pixelate-$os/* ;;
              esac
            fi
          done

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          gh release create "$TAG_NAME" pixelate_* \
            --title "$TAG_NAME" \
            --generate-notes
